In [1]:
import numpy as np

In [6]:
# önce 1 lerden oluşna 5x5 matrix oluşturduk
matrix = np.ones((5,5))
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# 0'lardan oluşan 3x3 matrix
matrix2 = np.zeros((3,3))
matrix2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# 1x1 lik dan oluşan bir matrix
matrix3 = np.array([9])
matrix3

array([9])

In [22]:
# matrix'in istediğimiz alanını sıfır yapmak için matrix2 (zeros) ye eşitledik
matrix[1:4,1:4] = matrix2
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#şidmdide ilk matriximizin ortasına son oluşturduğumuz matrixi yerleştireceğiz
matrix[2,2] = matrix3

In [24]:
#oluşturulması istenen matrix matrix
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
