# Numpy Nedir?
        Python için bir bilimsel hesaplama kütüphanesidir ve çok boyutlu dizilerle yüksek performanslı matematiksel işlemler yapmayı sağlar. Bu kütüphane, lineer cebir, rastgele sayı üretimi ve Fourier dönüşümleri gibi geniş bir matematiksel işlev yelpazesini destekler. Ayrıca, verimli veri işleme yetenekleri sunar ve genellikle veri analizi ve bilimsel hesaplama alanlarında kullanılır.
        
## Listeler ile farkı ne ?
        Listeler, Python'da genel amaçlı veri saklamak için kullanılırken, NumPy dizileri özellikle matematiksel işlemler ve büyük veri setleri üzerinde çalışmak için optimize edilmiş veri yapılarıdır. NumPy dizileri, bellek kullanımında daha verimli ve işlemlerde daha hızlıdır, bu nedenle büyük veri işleme ve bilimsel hesaplama için tercih edilir.

## 1- Numpy'ı dahil etme

In [12]:
import numpy as np

## 2 - Temeller

### 2.1 -  .array() ---> dizi oluşturma


In [20]:
#numpy kütüphanesinde array(dizi)'yi dahil edip içine liste ile elaman verdik, Tek boyutlu bir dizi
#dtype kısmını eklemek zorunlu değil, default olarak ekleniyor, ama biz bu örnekte küçük sayılar kullandığımız için int16 yaptık

a = np.array([1,2,3],dtype = "int16")
print(a)


[1 2 3]


In [21]:
# burada da bir listenin içine oluşturduğumuz iki ayrı liste ile iki boyutlu bir dizi oluşturmuş olduk

b = np.array( [[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]] )
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


### 2.2 - .ndim ---> dizinin boyutunu öğrenme

In [36]:
a.ndim
b.ndim

2

### 2.2.1 -  .shape ---> bir dizinin boyutunu (satır,sütun) şeklinde öğrenmek için


In [23]:
a.shape #çıktı olarak (3,) verecektir bu da bu dizinin tek boyutlu olduğunu ve o boyutta 3 adet elamanı olduğunu anlatır 

b.shape #ama bu tek boyutlu olmadığından (satır,sütun) kalıbına uygun şekilde çıktı verecektir

(2, 3)

### 2.3 - .dtype ---> Dizinin Veri Tipini Öğrenme

In [26]:
a.dtype # int32 çıktısını verecek
b.dtype # float64 çıktısını verecek

dtype('float64')

### 2.4 - .itemsize ---> dizinin öğelerinin tek tek bellekte kaç byte kapladığını öğrenme

In [31]:
#int16 yaptığımız için kapladığı alan daha az 32 yapsaydık iki katı kaplayacaktı
a.itemsize 

2

### 2.4.1 - toplam alanı öğrenme

In [35]:
#size bize eleman sayısını verir itemsize her elemanın kapladığı alanı bunların çarpımı bize toplan kaplanan alanı verir

a.size * a.itemsize

#veya direkt olarak aşşağıdaki şekilde de alabiliriz bu değeri 

a.nbytes

6