##  3 - Belirli öğelere, satırlara, sütunlara vb. erişme/değiştirme


In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Belirli bir elemana erişme , [satır , sütun]

In [7]:
# 1. satır 5. sütuna eriştik (indexler 0 dan başlıyor)

a[1,5]

# aynı zamanda negatif indexleme de yapılabilir aşağıdaki ifade yukarıdaki ile aynı elamanı verir

a[1, -2]

13

### Belirli bir satıra erişme

In [8]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

### Belirli bir sütuna erişme

In [9]:
a[:,2]

array([ 3, 10])

### Belli bir aralıktaki elemanları alma , [startindex : endindex : stepsize]

In [11]:
# ilk satır içinde işlem yaptık 1. indexten başlayıp 6. indexe kadar 2 şer 2 şer atladık

a[0, 1:6:2]

array([2, 4, 6])

### Elemanın değerini değiştirme

In [16]:
#2. satır 6. sütundaki elemanı(13 sayısını) 20 ile değiştirdik
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
#farklı kullanımları ---> 2. indexteki kolonun elemanlarını güncelledik 
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [21]:
#farklı değerler vermek istersek
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## Örnek (3 boyutlu dizi)

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#0. index dediğimizde 1,2/3,4 e erişiyoruz , 1 dediğimizde 3,4 de erişiriyoruz  tekrar 1 dediğimizde 4 e erişiyoruz

b[0,1,1]

4

In [32]:
#değiştirme işlemi yapmak istediğimizde

b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

[:,1,:] bunu şöyle düşünelim dıştan içe doğru
öncelikle ilk ":" işareti tüm diziyi seçmemizi sağlar, "1" ise bu dizi içindeki dizlerin 1. indexlerini seçmeye yarar
son ":" işareti ise dizilerin içindeki 1. indekslerin hepsini seçmemize yarar ve eşitlik verip değiştirme işlemi yaptığımızda ise yukarıdan aşağı doğru değişim gerçekleşir