### Tamamı 0 olan matris oluşturma

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
#istediğimiz boyutta matris oluşturabiliriz bu şekilde 

### Tamamı 1 olan matris

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### Tamamı istediğimiz sayıdan oluşan matris 

In [11]:
np.full((2,2,2), 32)

array([[[32, 32],
        [32, 32]],

       [[32, 32],
        [32, 32]]])

### Bir matrisin boyutlarını kullanarak istediğimiz sayıdan oluşan matris oluşturma

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
#a matrisi ile aynı boyutlara sahip 4 lerden oluşan matris oluşturma
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Random sayılarla matris oluşturma 

In [16]:
#5 e 2 lik bir matris oluşturup bunun elemanlarını random olarak atar 
np.random.rand(5,2)

array([[0.31798312, 0.15943629],
       [0.58071093, 0.30421865],
       [0.14319097, 0.49584615],
       [0.61903539, 0.55056226],
       [0.72105594, 0.52684643]])

In [17]:
np.random.rand(5,2,3)

array([[[0.89626158, 0.31902713, 0.82415319],
        [0.61499601, 0.22993806, 0.19648531]],

       [[0.96274169, 0.60706675, 0.12220699],
        [0.97076832, 0.21770406, 0.12871679]],

       [[0.54941099, 0.78948007, 0.7296286 ],
        [0.82791521, 0.41559961, 0.19938983]],

       [[0.28661256, 0.51128271, 0.36723712],
        [0.00966496, 0.18989765, 0.45802554]],

       [[0.99436686, 0.92782335, 0.15719683],
        [0.49201836, 0.65120511, 0.35999018]]])

In [22]:
#varolan bir matrisin boyutlarında rastgele matris oluşturma

np.random.random_sample(a.shape)

array([[0.834588  , 0.53036667, 0.98414886, 0.55612662, 0.70931386,
        0.45730873, 0.30938363],
       [0.31946954, 0.70837064, 0.44299721, 0.00752792, 0.8067791 ,
        0.499314  , 0.40136673]])

### Integer random değerlerle dizi oluşturma

In [26]:
np.random.randint(1,7,size = (5,7))

array([[4, 5, 1, 4, 4, 6, 6],
       [5, 5, 6, 1, 3, 5, 5],
       [2, 6, 5, 6, 6, 1, 3],
       [2, 1, 3, 1, 3, 6, 3],
       [5, 6, 6, 3, 6, 2, 1]])

### Birim Matris oluşturma

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#dizinin elemanlarını tekrarlama
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
