### !! Matrisi Kopyalarken dikkat

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = a
b
# bu şekilde kopyalama yaparsak b'den bir elemanı değiştirdiğimizde a' da da değişme olacaktır örn:
b[0] = 100 
b # çıktı [100 , 2 , 3] olacak 
a # bununda çıktısı [100 , 2 , 3] olacak
#yani ana matris değişmeden başka işlemler yapmak için bu şekilde kopyalama işlemi yaparsanız ana matrisi de değiştirirsiniz

array([100,   2,   3])

In [4]:
#bu sorunlar karşılaşmamak için aşağıdaki işlem yapılabilir 
c = np.array([1,2,3])
d = c.copy()

## Matematik

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
#bu şekilde 4 işlemi ve bununla beraber temel operatörleri de uygulayabiliriz += -= vs.
arr + 2
arr - 2
arr * 2
arr / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
arr2 = np.array([1,0,1,0])
arr2

array([1, 0, 1, 0])

In [8]:
#iki matrisi de toplayabiliriz
arr + arr2

array([2, 2, 4, 4])

In [9]:
#üs alma işlemi 
arr ** 2 

array([ 1,  4,  9, 16])

In [10]:
#sinus ve cosinus alma
np.sin(arr)
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [11]:
## daha fazla işlemi numpy.org üzerinden inceleyebilirsiniz

## Lineer Cebir

In [12]:
a = np.ones((2,3))
b = np.full((3,2),2)

### Çarpma işlemi


In [13]:
#çarpma işlemi yapılabilmesi için : birinci matrisin sütun sayısının ikinci matrisin satır sayısına eşit olmasıdır.
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

### Determinant alma

In [18]:
#Determinant kare matrisler için hesaplanan reel sayı bir değerdir ve matrislerin tersinin bulunmasında
# ve lineer denklem sistemlerinin çözümünde kullanılır.

c = np.identity(3)
np.linalg.det(c)

1.0

### Transpoze

In [22]:
#orijinal matristeki satırların ve sütunların yer değiştirilmesiyle elde edilen yeni bir matristir
c = np.array(([1,2,3],
              [4,5,6],
              [7,8,9]))

np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Matrisin Tersi

In [23]:
#Bir matrisin tersi, matrisin kendisi ile çarpıldığına birim matrisi veren matristir.
d = np.array(([1,2,3],
              [4,5,6],
              [7,8,9]))

np.linalg.inv(d)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

### Çözümleme

In [ ]:
#bir matrisin bir vektöre çarpılması sonucu başka bir vektörü veren lineer bir denklem sisteminin çözümünü bulma işlemidir.

