In [1]:
import numpy as np

In [2]:
a = np.array(([1,2,3],[4,5,6]))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# minimum ve maksimum değeri bulma
np.min(a)
np.max(a)

6

In [6]:
# aynı şekilde satır bazında min max işlemi de yaptırabiliriz
np.min(a,axis=1)

array([1, 4])

In [7]:
# matrisin elemanlarının toplamını alma
np.sum(a)

21

### Matrisin boyutunu değiştirme

In [20]:
#elimizde aşağıdaki matris olsun 
onceki_boyut = np.array([[1,2,3,4],
                        [5,6,7,8]])
#(2,4) lük bir matris var elimizde biz bunu istediğimiz şekilde şekillendirebiliriz ((a,b,c) --> a*b*c = matris.size)
onceki_boyut.shape

8

In [22]:
sekillendirilmis_matris = onceki_boyut.reshape((2,4))
sekillendirilmis_matris

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Vektörleri birleştirme (dikey olarak)

In [24]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Vektörleri birleştirme (yatay olarak)

In [27]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Çeşitli İşlemler

#### Dosyadan data yükleme

In [50]:
#dosyayı sisteme aktardık
file_data = np.genfromtxt("data.txt",delimiter=",")
file_data = file_data.astype("int32")
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [52]:
new_file_data = file_data.reshape((9,6))
new_file_data

array([[  1,  13,  21,  11, 196,  75],
       [  4,   3,  34,   6,   7,   8],
       [  0,   1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75],
       [  4,  55,   6,   4,   3,   4],
       [  5,   6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11],
       [  2,   1,  78,   0,   1,   2],
       [  9,   8,   7,   1,  76,  88]])

### Boolean Masking ve Gelişmiş İndexleme

In [53]:
#bu şekilde yaparsak bize true false değerlerini gösterir
new_file_data > 50

array([[False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False,  True, False, False, False],
       [False, False, False, False,  True,  True]])

In [55]:
#ama bu şekilde yaparsak bize büyük olan değerlerin dizisini verir
new_file_data[new_file_data>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [58]:
#herhangi bir elemanın 50den büyük olup olmadığını kontrol eder 1 tane bile büyük varsa true döner 
np.any(new_file_data > 50)

True

In [60]:
#sütunlara bakar çıktıdaki her bir ifade sırasıyla sütunları ifade eder
np.any(new_file_data > 50, axis=0)

array([False,  True,  True, False,  True,  True])

In [61]:
#satırları ifade eder yukarıdakiyle aynı mantıkta 
np.any(new_file_data > 50 , axis=1)

array([ True, False, False,  True,  True, False,  True,  True,  True])

In [62]:
#bu şekilde if else işlemlerinde kullandığımız operatörlerle işlemler yapılabilir
((new_file_data>50) & (new_file_data<100))

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False,  True,  True]])

In [64]:
#bu kullanımla da direkt olarak şartı sağlayan ifadeleri görebiliriz
new_file_data[((new_file_data>50) & (new_file_data<100))]

array([75, 75, 55, 78, 76, 88])

In [65]:
#yukarıdaki ifadenin tam tersini almak istiyorsak 
(~(new_file_data>50) & (new_file_data<100))

array([[ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [ True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True, False, False]])